### ISSUE TITLE
Error: No object named table in the file

### ISSUE THREAD

**Issue by paularindam** [maxhodak/keras-molecules#3] opened 2016-10-25 15:53 UTC
Hi 
On running 
python preprocess.py data/dataset.h5 data/processed.h5

I get an error: no object named table in the file. 
<img width="1275" alt="screenshot 2016-10-25 10 52 21" src="https://cloud.githubusercontent.com/assets/2607180/19693451/3489424a-9aa1-11e6-9d75-c92a8c44b61d.png">

**Comment by maxhodak** [comment] 2016-10-25 17:12
Did you create a valid HDF5 file at `data/dataset.h5`? Those are just placeholders in the README. If you don't have a dataset of your own, you can use the example one:

`python preprocess.py data/smiles_50k.h5 data/processed.h5`

**Comment by maxhodak** [comment] 2016-10-26 01:25
This works for me so if the issue is just the file being nonexistent in your example above I'm going to close this. Feel free to reopen if I've misinterpreted the issue.

**Closed as completed by maxhodak** 2016-10-26 01:25 UTC
